{
 "title": "DbETS Elixir",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Reads Times",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "db_ets_records_read_stop_duration_bucket",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "DB records writes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_ets_records_write_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB records count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_ets_records_count", "legendFormat": "__auto" }
   ]
  }
 ]
}